# Generated by Django 5.0.6 on 2024-07-23 05:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_courses_enrolled_course_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 7, 23, 5, 34, 34, 62193, tzinfo=datetime.timezone.utc))),
                ('gdrive_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='registration_fees',
        ),
        migrations.AddField(
            model_name='course',
            name='batch_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Weekend', 'Weekend')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 5, 35, 31, 234835, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 5, 34, 34, 63185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 7, 23, 5, 34, 34, 64184, tzinfo=datetime.timezone.utc))),
                ('price', models.IntegerField(blank=True, null=True)),
                ('installment_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='recording_sessions',
            field=models.ManyToManyField(to='app.sessions'),
        ),
    ]
