# Generated by Django 5.0.6 on 2024-07-23 06:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_course_starting_date_alter_installment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 6, 40, 14, 724164, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='installment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 6, 40, 14, 725165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='installment',
            name='user',
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 6, 40, 14, 723165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='installment',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
