# Generated by Django 5.0.6 on 2024-08-28 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_course_content_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='batch_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Weekend', 'Weekend'), ('Intern', 'Intern'), ('Cross-Spilling', 'Cross-Spilling'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Who Can Enroll this Course?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 28, 6, 46, 18, 773930, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='installment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 6, 46, 18, 774930, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 6, 46, 18, 772930, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 6, 46, 18, 772930, tzinfo=datetime.timezone.utc)),
        ),
    ]
