# Generated by Django 5.0.6 on 2024-08-28 06:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_course_content_alter_course_starting_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='date',
        ),
        migrations.AddField(
            model_name='installment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 28, 6, 54, 15, 165904, tzinfo=datetime.timezone.utc), verbose_name='Installment Due Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_fees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Course Registration fees'),
        ),
        migrations.AlterField(
            model_name='course',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 28, 6, 54, 15, 162906, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='installment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Installment Amount'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 6, 54, 15, 161903, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 6, 54, 15, 161903, tzinfo=datetime.timezone.utc)),
        ),
    ]
