# Generated by Django 5.0.6 on 2024-09-06 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_installment_date_installment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 6, 12, 25, 57, 412007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 6, 12, 25, 57, 407877, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 6, 12, 25, 57, 409939, tzinfo=datetime.timezone.utc), verbose_name='Installment Due Date'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 12, 25, 57, 406847, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 12, 25, 57, 407877, tzinfo=datetime.timezone.utc)),
        ),
    ]
